// Sugestões de agentes/riscos mais comuns por tipo (fis/qui/bio/erg/aci/psi),
// usadas como datalist no campo "Agente / risco" do inventário do PGR — o
// usuário pode digitar livremente, isso só acelera o preenchimento.

export const AGENTES_POR_TIPO: Record<string, string[]> = {
  fis: [
    'Ruído contínuo ou intermitente',
    'Ruído de impacto',
    'Calor',
    'Frio',
    'Vibração de corpo inteiro',
    'Vibração de mãos e braços',
    'Radiações ionizantes',
    'Radiações não ionizantes',
    'Pressão hiperbárica (mergulho/hiperbárico)',
    'Umidade',
    'Infrassom / ultrassom',
    'Eletricidade estática',
  ],
  qui: [
    'Poeiras minerais (sílica)',
    'Poeiras de origem vegetal ou animal',
    'Fumos metálicos',
    'Névoas',
    'Neblinas',
    'Gases e vapores tóxicos',
    'Solventes orgânicos',
    'Hidrocarbonetos e outros compostos de carbono',
    'Ácidos e álcalis cáusticos',
    'Agrotóxicos / praguicidas',
    'Chumbo e seus compostos',
    'Benzeno e compostos aromáticos (tolueno, xileno)',
    'Asbesto (amianto)',
    'Sílica livre cristalizada',
    'Cromo e seus compostos',
    'Mercúrio e seus compostos',
    'Arsênio e seus compostos',
    'Manganês e seus compostos',
    'Fósforo e compostos (organofosforados)',
  ],
  bio: [
    'Vírus',
    'Bactérias',
    'Fungos',
    'Parasitas (protozoários e helmintos)',
    'Bacilos',
    'Material biológico contaminado',
    'Resíduos e/ou objetos infectocontagiantes (perfurocortantes, lixo, esgoto)',
    'Contato com pacientes/animais em ambiente de saúde',
  ],
  erg: [
    'Postura inadequada',
    'Levantamento e transporte manual de carga',
    'Movimentos repetitivos',
    'Jornada de trabalho prolongada',
    'Monotonia e repetitividade',
    'Trabalho em turnos e/ou noturno',
    'Mobiliário/posto de trabalho inadequado',
    'Ritmo excessivo de trabalho',
    'Iluminação inadequada',
    'Trabalho em pé por período prolongado',
  ],
  aci: [
    'Queda de altura',
    'Queda de mesmo nível',
    'Corte / objeto perfurocortante',
    'Prensamento / esmagamento',
    'Choque elétrico',
    'Incêndio / explosão',
    'Atropelamento / colisão veicular',
    'Projeção de partículas',
    'Arranjo físico inadequado',
    'Máquinas e equipamentos sem proteção',
    'Armazenamento inadequado',
  ],
  psi: [
    'Assédio moral',
    'Assédio sexual',
    'Sobrecarga de trabalho',
    'Estresse ocupacional',
    'Burnout / esgotamento profissional',
    'Violência no trabalho',
    'Conflitos interpessoais',
    'Insegurança no emprego',
    'Metas excessivas / pressão por produtividade',
  ],
}
