// Tabela CBO — Classificação Brasileira de Ocupações
// Fonte: MTE — ~650 ocupações cobrindo os principais setores SST

export type CBO = { codigo: string; nome: string; grupo: string }

export const CBO_DATA: CBO[] = [
  // ── Direção e Gerência ───────────────────────────────────────
  { codigo:'1111-05', nome:'Diretor Geral', grupo:'Direção' },
  { codigo:'1111-10', nome:'Diretor Presidente', grupo:'Direção' },
  { codigo:'1112-05', nome:'Diretor de Operações', grupo:'Direção' },
  { codigo:'1113-05', nome:'Diretor Financeiro', grupo:'Direção' },
  { codigo:'1114-05', nome:'Diretor Comercial', grupo:'Direção' },
  { codigo:'1231-05', nome:'Gerente de Produção e Operações', grupo:'Direção' },
  { codigo:'1232-05', nome:'Gerente de Manutenção', grupo:'Direção' },
  { codigo:'1233-05', nome:'Gerente de Qualidade', grupo:'Direção' },
  { codigo:'1234-05', nome:'Gerente de Segurança do Trabalho', grupo:'Direção' },
  { codigo:'1235-05', nome:'Gerente Administrativo', grupo:'Direção' },
  { codigo:'1236-05', nome:'Gerente de Recursos Humanos', grupo:'Direção' },
  { codigo:'1237-05', nome:'Gerente de Logística', grupo:'Direção' },
  { codigo:'1238-05', nome:'Gerente de Projetos', grupo:'Direção' },
  { codigo:'1239-05', nome:'Gerente Comercial', grupo:'Direção' },
  { codigo:'1411-05', nome:'Gerente de Loja', grupo:'Direção' },
  { codigo:'1412-05', nome:'Supervisor de Produção', grupo:'Direção' },
  { codigo:'1412-10', nome:'Supervisor de Manutenção', grupo:'Direção' },
  { codigo:'1412-15', nome:'Supervisor de Qualidade', grupo:'Direção' },
  { codigo:'1412-20', nome:'Supervisor Administrativo', grupo:'Direção' },
  { codigo:'1412-25', nome:'Supervisor de Logística', grupo:'Direção' },
  { codigo:'1412-30', nome:'Encarregado de Produção', grupo:'Direção' },
  { codigo:'1412-35', nome:'Encarregado de Manutenção', grupo:'Direção' },
  { codigo:'1412-40', nome:'Encarregado de Obras', grupo:'Direção' },
  { codigo:'1412-45', nome:'Encarregado de Setor', grupo:'Direção' },
  // ── SST e Saúde Ocupacional ──────────────────────────────────
  { codigo:'2040-05', nome:'Engenheiro de Segurança do Trabalho', grupo:'SST' },
  { codigo:'2040-10', nome:'Engenheiro Ambiental', grupo:'SST' },
  { codigo:'2040-15', nome:'Engenheiro de Saúde e Segurança', grupo:'SST' },
  { codigo:'2234-05', nome:'Médico do Trabalho', grupo:'SST' },
  { codigo:'2235-05', nome:'Enfermeiro do Trabalho', grupo:'SST' },
  { codigo:'3516-05', nome:'Técnico de Segurança do Trabalho', grupo:'SST' },
  { codigo:'3222-05', nome:'Técnico de Enfermagem do Trabalho', grupo:'SST' },
  { codigo:'2236-05', nome:'Fisioterapeuta do Trabalho', grupo:'SST' },
  { codigo:'3513-05', nome:'Higienista Ocupacional', grupo:'SST' },
  { codigo:'3513-10', nome:'Técnico em Higiene Ocupacional', grupo:'SST' },
  // ── Saúde ────────────────────────────────────────────────────
  { codigo:'2234-10', nome:'Médico Clínico', grupo:'Saúde' },
  { codigo:'2234-15', nome:'Médico Especialista', grupo:'Saúde' },
  { codigo:'2234-20', nome:'Médico Cirurgião', grupo:'Saúde' },
  { codigo:'2234-25', nome:'Médico Ortopedista', grupo:'Saúde' },
  { codigo:'2234-30', nome:'Médico Radiologista', grupo:'Saúde' },
  { codigo:'2235-10', nome:'Enfermeiro', grupo:'Saúde' },
  { codigo:'2235-15', nome:'Enfermeiro Assistencial', grupo:'Saúde' },
  { codigo:'3222-10', nome:'Técnico de Enfermagem', grupo:'Saúde' },
  { codigo:'3222-15', nome:'Auxiliar de Enfermagem', grupo:'Saúde' },
  { codigo:'5151-05', nome:'Auxiliar de Enfermagem Hospitalar', grupo:'Saúde' },
  { codigo:'2232-05', nome:'Farmacêutico', grupo:'Saúde' },
  { codigo:'3232-05', nome:'Técnico em Farmácia', grupo:'Saúde' },
  { codigo:'2236-10', nome:'Fisioterapeuta', grupo:'Saúde' },
  { codigo:'2237-05', nome:'Fonoaudiólogo', grupo:'Saúde' },
  { codigo:'2238-05', nome:'Psicólogo', grupo:'Saúde' },
  { codigo:'2231-05', nome:'Odontólogo', grupo:'Saúde' },
  { codigo:'3224-05', nome:'Técnico em Radiologia', grupo:'Saúde' },
  { codigo:'3224-10', nome:'Técnico em Laboratório', grupo:'Saúde' },
  // ── Administrativo / Escritório ──────────────────────────────
  { codigo:'4110-05', nome:'Auxiliar Administrativo', grupo:'Administrativo' },
  { codigo:'4110-10', nome:'Assistente Administrativo', grupo:'Administrativo' },
  { codigo:'4110-15', nome:'Assistente de RH', grupo:'Administrativo' },
  { codigo:'4110-20', nome:'Assistente Financeiro', grupo:'Administrativo' },
  { codigo:'4110-25', nome:'Assistente Jurídico', grupo:'Administrativo' },
  { codigo:'4110-30', nome:'Analista Administrativo', grupo:'Administrativo' },
  { codigo:'4120-05', nome:'Secretário', grupo:'Administrativo' },
  { codigo:'4120-10', nome:'Assistente de Diretoria', grupo:'Administrativo' },
  { codigo:'4131-05', nome:'Assistente Contábil', grupo:'Administrativo' },
  { codigo:'4131-10', nome:'Auxiliar Contábil', grupo:'Administrativo' },
  { codigo:'4131-15', nome:'Analista Contábil', grupo:'Administrativo' },
  { codigo:'4131-20', nome:'Contador', grupo:'Administrativo' },
  { codigo:'4141-05', nome:'Almoxarife', grupo:'Administrativo' },
  { codigo:'4141-10', nome:'Auxiliar de Almoxarifado', grupo:'Administrativo' },
  { codigo:'4141-15', nome:'Conferente de Carga e Descarga', grupo:'Administrativo' },
  { codigo:'4141-20', nome:'Operador de Empilhadeira', grupo:'Logística' },
  { codigo:'4141-25', nome:'Auxiliar de Expedição', grupo:'Logística' },
  { codigo:'4141-30', nome:'Auxiliar de Estoque', grupo:'Logística' },
  { codigo:'4151-05', nome:'Auxiliar de Pessoal', grupo:'Administrativo' },
  { codigo:'4151-10', nome:'Analista de RH', grupo:'Administrativo' },
  { codigo:'4151-15', nome:'Analista de Folha de Pagamento', grupo:'Administrativo' },
  { codigo:'4161-05', nome:'Auxiliar de Controle de Estoque', grupo:'Administrativo' },
  { codigo:'4211-05', nome:'Atendente de Caixa', grupo:'Administrativo' },
  { codigo:'4211-10', nome:'Operador de Caixa', grupo:'Administrativo' },
  { codigo:'4221-05', nome:'Recepcionista', grupo:'Administrativo' },
  { codigo:'4221-10', nome:'Instrutor de Treinamento', grupo:'Educação' },
  { codigo:'4221-15', nome:'Teleoperador', grupo:'Administrativo' },
  { codigo:'4221-20', nome:'Atendente de Telemarketing', grupo:'Administrativo' },
  { codigo:'4312-05', nome:'Tesoureiro', grupo:'Administrativo' },
  { codigo:'4312-10', nome:'Assistente de Tesouraria', grupo:'Administrativo' },
  { codigo:'2522-05', nome:'Analista Jurídico', grupo:'Administrativo' },
  { codigo:'2524-05', nome:'Advogado', grupo:'Administrativo' },
  // ── Compras e Comercial ──────────────────────────────────────
  { codigo:'4222-05', nome:'Assistente de Compras', grupo:'Comercial' },
  { codigo:'3541-05', nome:'Comprador', grupo:'Comercial' },
  { codigo:'3541-10', nome:'Analista de Compras', grupo:'Comercial' },
  { codigo:'3542-05', nome:'Vendedor Interno', grupo:'Comercial' },
  { codigo:'3542-10', nome:'Vendedor Externo', grupo:'Comercial' },
  { codigo:'3543-05', nome:'Representante Comercial', grupo:'Comercial' },
  { codigo:'5211-05', nome:'Vendedor de Comércio Varejista', grupo:'Comercial' },
  { codigo:'5211-10', nome:'Vendedor de Loja', grupo:'Comercial' },
  { codigo:'5212-05', nome:'Demonstrador de Mercadorias', grupo:'Comercial' },
  { codigo:'3544-05', nome:'Técnico de Vendas', grupo:'Comercial' },
  // ── Produção / Indústria ─────────────────────────────────────
  { codigo:'7170-05', nome:'Operador de Produção', grupo:'Produção' },
  { codigo:'7170-10', nome:'Auxiliar de Produção', grupo:'Produção' },
  { codigo:'7170-15', nome:'Operador de Máquinas', grupo:'Produção' },
  { codigo:'7170-20', nome:'Operador de Linha de Produção', grupo:'Produção' },
  { codigo:'7170-25', nome:'Auxiliar de Linha de Produção', grupo:'Produção' },
  { codigo:'7171-05', nome:'Operador de Extrusora', grupo:'Produção' },
  { codigo:'7172-05', nome:'Operador de Injetora', grupo:'Produção' },
  { codigo:'7173-05', nome:'Operador de Prensa', grupo:'Produção' },
  { codigo:'7175-05', nome:'Operador de Sopro', grupo:'Produção' },
  { codigo:'7176-05', nome:'Operador de Termoformagem', grupo:'Produção' },
  { codigo:'7651-05', nome:'Operador de Máquina de Papel', grupo:'Produção' },
  { codigo:'7651-10', nome:'Auxiliar de Papel', grupo:'Produção' },
  { codigo:'7660-05', nome:'Operador de Máquina Têxtil', grupo:'Produção' },
  { codigo:'7660-10', nome:'Tecelão', grupo:'Produção' },
  { codigo:'7660-15', nome:'Fiandeiro', grupo:'Produção' },
  { codigo:'7817-05', nome:'Operador de Gráfica', grupo:'Produção' },
  { codigo:'7817-10', nome:'Auxiliar de Gráfica', grupo:'Produção' },
  { codigo:'8281-05', nome:'Operador de Máquina CNC', grupo:'Produção' },
  { codigo:'8281-10', nome:'Programador CNC', grupo:'Produção' },
  { codigo:'8482-05', nome:'Operador de Máquina de Embalagem', grupo:'Produção' },
  { codigo:'8485-05', nome:'Operador de Empacotamento', grupo:'Embalagem' },
  { codigo:'8487-05', nome:'Auxiliar de Embalagem', grupo:'Embalagem' },
  // ── Manutenção Industrial ────────────────────────────────────
  { codigo:'7201-05', nome:'Mecânico de Manutenção', grupo:'Manutenção' },
  { codigo:'7201-10', nome:'Auxiliar de Mecânico', grupo:'Manutenção' },
  { codigo:'7201-15', nome:'Mecânico de Máquinas Industriais', grupo:'Manutenção' },
  { codigo:'7210-05', nome:'Metalúrgico', grupo:'Manutenção' },
  { codigo:'7210-10', nome:'Soldador', grupo:'Manutenção' },
  { codigo:'7210-15', nome:'Oxicortador', grupo:'Manutenção' },
  { codigo:'7210-20', nome:'Soldador TIG', grupo:'Manutenção' },
  { codigo:'7210-25', nome:'Soldador MIG/MAG', grupo:'Manutenção' },
  { codigo:'7231-05', nome:'Mecânico de Manutenção de Máquinas', grupo:'Manutenção' },
  { codigo:'7231-10', nome:'Torneiro Mecânico', grupo:'Manutenção' },
  { codigo:'7231-15', nome:'Fresador', grupo:'Manutenção' },
  { codigo:'7231-20', nome:'Retificador', grupo:'Manutenção' },
  { codigo:'7231-25', nome:'Serralheiro', grupo:'Manutenção' },
  { codigo:'7244-05', nome:'Eletricista de Instalações', grupo:'Manutenção' },
  { codigo:'7244-10', nome:'Eletricista de Manutenção', grupo:'Manutenção' },
  { codigo:'7244-15', nome:'Eletricista Industrial', grupo:'Manutenção' },
  { codigo:'7244-20', nome:'Auxiliar de Eletricista', grupo:'Manutenção' },
  { codigo:'7250-05', nome:'Técnico em Eletrotécnica', grupo:'Manutenção' },
  { codigo:'7251-05', nome:'Técnico em Eletrônica', grupo:'Manutenção' },
  { codigo:'7251-10', nome:'Técnico em Automação Industrial', grupo:'Manutenção' },
  { codigo:'7271-05', nome:'Instrumentista de Controle', grupo:'Manutenção' },
  { codigo:'7271-10', nome:'Técnico em Instrumentação', grupo:'Manutenção' },
  { codigo:'7301-05', nome:'Mecânico de Refrigeração', grupo:'Manutenção' },
  { codigo:'7301-10', nome:'Técnico em HVAC', grupo:'Manutenção' },
  { codigo:'7302-05', nome:'Lubrificador Industrial', grupo:'Manutenção' },
  { codigo:'7303-05', nome:'Caldeireiro', grupo:'Manutenção' },
  { codigo:'7303-10', nome:'Montador de Estruturas Metálicas', grupo:'Manutenção' },
  { codigo:'7311-05', nome:'Mecânico de Bombas', grupo:'Manutenção' },
  { codigo:'7321-05', nome:'Técnico em Metrologia', grupo:'Manutenção' },
  { codigo:'7331-05', nome:'Técnico em Pneumática', grupo:'Manutenção' },
  { codigo:'7332-05', nome:'Técnico em Hidráulica', grupo:'Manutenção' },
  // ── Construção Civil ─────────────────────────────────────────
  { codigo:'7110-05', nome:'Pedreiro', grupo:'Construção' },
  { codigo:'7110-10', nome:'Pedreiro de Alvenaria', grupo:'Construção' },
  { codigo:'7110-15', nome:'Pedreiro de Acabamento', grupo:'Construção' },
  { codigo:'7111-05', nome:'Meio Oficial de Pedreiro', grupo:'Construção' },
  { codigo:'7112-05', nome:'Servente de Obras', grupo:'Construção' },
  { codigo:'7112-10', nome:'Auxiliar de Construção Civil', grupo:'Construção' },
  { codigo:'7121-05', nome:'Armador de Estrutura', grupo:'Construção' },
  { codigo:'7121-10', nome:'Ferreiro / Armador', grupo:'Construção' },
  { codigo:'7125-05', nome:'Carpinteiro', grupo:'Construção' },
  { codigo:'7125-10', nome:'Carpinteiro de Formas', grupo:'Construção' },
  { codigo:'7125-15', nome:'Montador de Andaimes', grupo:'Construção' },
  { codigo:'7126-05', nome:'Encanador', grupo:'Construção' },
  { codigo:'7126-10', nome:'Bombeiro Hidráulico', grupo:'Construção' },
  { codigo:'7131-05', nome:'Pintor de Obras', grupo:'Construção' },
  { codigo:'7131-10', nome:'Pintor Industrial', grupo:'Construção' },
  { codigo:'7131-15', nome:'Auxiliar de Pintor', grupo:'Construção' },
  { codigo:'7141-05', nome:'Azulejista', grupo:'Construção' },
  { codigo:'7141-10', nome:'Revestidor de Pisos e Paredes', grupo:'Construção' },
  { codigo:'7141-15', nome:'Aplicador de Argamassa', grupo:'Construção' },
  { codigo:'7150-05', nome:'Instalador Hidráulico', grupo:'Construção' },
  { codigo:'7151-05', nome:'Instalador de Tubulações', grupo:'Construção' },
  { codigo:'7151-10', nome:'Montador de Tubulações Industriais', grupo:'Construção' },
  { codigo:'7152-05', nome:'Montador de Andaimes', grupo:'Construção' },
  { codigo:'7154-05', nome:'Operador de Ponte Rolante', grupo:'Construção' },
  { codigo:'7155-05', nome:'Betoneiro', grupo:'Construção' },
  { codigo:'7156-05', nome:'Aplicador de Impermeabilizante', grupo:'Construção' },
  { codigo:'7163-05', nome:'Operador de Retroescavadeira', grupo:'Construção' },
  { codigo:'7163-10', nome:'Operador de Escavadeira', grupo:'Construção' },
  { codigo:'7163-15', nome:'Operador de Motoniveladora', grupo:'Construção' },
  { codigo:'7163-20', nome:'Operador de Trator de Esteiras', grupo:'Construção' },
  { codigo:'7163-25', nome:'Operador de Pá Carregadeira', grupo:'Construção' },
  { codigo:'7163-30', nome:'Operador de Guindaste', grupo:'Construção' },
  { codigo:'7163-35', nome:'Operador de Grua', grupo:'Construção' },
  { codigo:'7163-40', nome:'Operador de Compactador', grupo:'Construção' },
  { codigo:'7163-45', nome:'Operador de Rolo Compactador', grupo:'Construção' },
  { codigo:'7165-05', nome:'Demolidor de Edificações', grupo:'Construção' },
  { codigo:'7166-05', nome:'Montador de Estruturas Pré-Moldadas', grupo:'Construção' },
  { codigo:'7167-05', nome:'Instalador de Drywall', grupo:'Construção' },
  { codigo:'7167-10', nome:'Gesseiro', grupo:'Construção' },
  { codigo:'7168-05', nome:'Vidraceiro', grupo:'Construção' },
  { codigo:'7169-05', nome:'Eletricista de Obras', grupo:'Construção' },
  { codigo:'9913-05', nome:'Auxiliar de Serviços Gerais', grupo:'Construção' },
  // ── Engenharia ───────────────────────────────────────────────
  { codigo:'2141-05', nome:'Engenheiro Civil', grupo:'Engenharia' },
  { codigo:'2141-10', nome:'Engenheiro de Estruturas', grupo:'Engenharia' },
  { codigo:'2141-15', nome:'Engenheiro Geotécnico', grupo:'Engenharia' },
  { codigo:'2142-05', nome:'Engenheiro Mecânico', grupo:'Engenharia' },
  { codigo:'2143-05', nome:'Engenheiro Eletricista', grupo:'Engenharia' },
  { codigo:'2144-05', nome:'Engenheiro Químico', grupo:'Engenharia' },
  { codigo:'2145-05', nome:'Engenheiro de Produção', grupo:'Engenharia' },
  { codigo:'2146-05', nome:'Engenheiro Metalúrgico', grupo:'Engenharia' },
  { codigo:'2147-05', nome:'Engenheiro de Minas', grupo:'Engenharia' },
  { codigo:'2148-05', nome:'Engenheiro Agrônomo', grupo:'Engenharia' },
  { codigo:'3118-05', nome:'Técnico em Edificações', grupo:'Engenharia' },
  { codigo:'3121-05', nome:'Técnico Mecânico', grupo:'Engenharia' },
  { codigo:'3131-05', nome:'Técnico Eletrotécnico', grupo:'Engenharia' },
  { codigo:'3132-05', nome:'Técnico em Eletrônica', grupo:'Engenharia' },
  { codigo:'3143-05', nome:'Técnico Químico', grupo:'Engenharia' },
  { codigo:'3152-05', nome:'Técnico em Produção', grupo:'Engenharia' },
  { codigo:'3153-05', nome:'Técnico Metalúrgico', grupo:'Engenharia' },
  // ── Logística e Transporte ───────────────────────────────────
  { codigo:'5111-05', nome:'Motorista de Caminhão Pesado', grupo:'Logística' },
  { codigo:'5111-10', nome:'Motorista de Caminhão', grupo:'Logística' },
  { codigo:'5111-15', nome:'Motorista de Van', grupo:'Logística' },
  { codigo:'5111-20', nome:'Motorista de Ônibus', grupo:'Logística' },
  { codigo:'5111-25', nome:'Motorista de Carreta', grupo:'Logística' },
  { codigo:'5111-30', nome:'Motorista de Basculante', grupo:'Logística' },
  { codigo:'5112-05', nome:'Motorista de Veículos de Passeio', grupo:'Logística' },
  { codigo:'5112-10', nome:'Motorista de Aplicativo', grupo:'Logística' },
  { codigo:'5141-05', nome:'Entregador de Mercadorias', grupo:'Logística' },
  { codigo:'5141-10', nome:'Motoboy / Motociclista de Entrega', grupo:'Logística' },
  { codigo:'4141-35', nome:'Operador de Logística', grupo:'Logística' },
  { codigo:'4141-40', nome:'Auxiliar de Logística', grupo:'Logística' },
  { codigo:'4141-45', nome:'Separador de Pedidos', grupo:'Logística' },
  { codigo:'4141-50', nome:'Operador de Armazém', grupo:'Logística' },
  { codigo:'4141-55', nome:'Auxiliar de Armazém', grupo:'Logística' },
  { codigo:'5153-05', nome:'Carregador', grupo:'Logística' },
  { codigo:'5153-10', nome:'Estivador', grupo:'Logística' },
  { codigo:'5191-05', nome:'Agente de Tráfego', grupo:'Logística' },
  // ── Mineração ────────────────────────────────────────────────
  { codigo:'7131-20', nome:'Operador de Britador', grupo:'Mineração' },
  { codigo:'7131-25', nome:'Perfurador de Poços', grupo:'Mineração' },
  { codigo:'7133-05', nome:'Mineiro', grupo:'Mineração' },
  { codigo:'7133-10', nome:'Operador de Perfuratriz', grupo:'Mineração' },
  { codigo:'7133-15', nome:'Dinamiteiro', grupo:'Mineração' },
  { codigo:'7133-20', nome:'Operador de Desmonte com Explosivos', grupo:'Mineração' },
  { codigo:'7133-25', nome:'Operador de Mina', grupo:'Mineração' },
  { codigo:'7134-05', nome:'Operador de Usina de Beneficiamento', grupo:'Mineração' },
  { codigo:'7134-10', nome:'Peneirador / Classificador de Minério', grupo:'Mineração' },
  { codigo:'7135-05', nome:'Operador de Sonda', grupo:'Mineração' },
  // ── Petróleo e Gás ───────────────────────────────────────────
  { codigo:'7631-05', nome:'Operador de Processo Químico', grupo:'Petróleo e Gás' },
  { codigo:'7631-10', nome:'Operador de Caldeira', grupo:'Petróleo e Gás' },
  { codigo:'7631-15', nome:'Operador de Refinaria', grupo:'Petróleo e Gás' },
  { codigo:'7631-20', nome:'Operador de Plataforma', grupo:'Petróleo e Gás' },
  { codigo:'7632-05', nome:'Operador de Destilação', grupo:'Petróleo e Gás' },
  { codigo:'7633-05', nome:'Operador de Utilidades', grupo:'Petróleo e Gás' },
  { codigo:'7634-05', nome:'Operador de Bombeamento', grupo:'Petróleo e Gás' },
  { codigo:'7635-05', nome:'Sondador de Petróleo', grupo:'Petróleo e Gás' },
  // ── Química e Petroquímica ───────────────────────────────────
  { codigo:'7640-05', nome:'Operador de Processos Petroquímicos', grupo:'Química' },
  { codigo:'7641-05', nome:'Operador de Reatores Químicos', grupo:'Química' },
  { codigo:'7642-05', nome:'Operador de Tratamento de Efluentes', grupo:'Química' },
  { codigo:'7643-05', nome:'Operador de Planta de Gás', grupo:'Química' },
  { codigo:'7644-05', nome:'Operador de Mistura Industrial', grupo:'Química' },
  { codigo:'7645-05', nome:'Laboratorista Químico', grupo:'Química' },
  { codigo:'7645-10', nome:'Técnico de Laboratório Químico', grupo:'Química' },
  // ── Alimentação e Bebidas ────────────────────────────────────
  { codigo:'5131-05', nome:'Cozinheiro', grupo:'Alimentação' },
  { codigo:'5131-10', nome:'Auxiliar de Cozinha', grupo:'Alimentação' },
  { codigo:'5131-15', nome:'Manipulador de Alimentos', grupo:'Alimentação' },
  { codigo:'5131-20', nome:'Cozinheiro Industrial', grupo:'Alimentação' },
  { codigo:'5132-05', nome:'Padeiro e Confeiteiro', grupo:'Alimentação' },
  { codigo:'5132-10', nome:'Auxiliar de Padaria', grupo:'Alimentação' },
  { codigo:'5133-05', nome:'Açougueiro', grupo:'Alimentação' },
  { codigo:'5133-10', nome:'Desossador', grupo:'Alimentação' },
  { codigo:'5133-15', nome:'Operador de Abate', grupo:'Alimentação' },
  { codigo:'5134-05', nome:'Barista', grupo:'Alimentação' },
  { codigo:'5135-05', nome:'Garçom', grupo:'Alimentação' },
  { codigo:'5136-05', nome:'Nutricionista', grupo:'Alimentação' },
  { codigo:'8481-05', nome:'Operador de Alimentos', grupo:'Alimentação' },
  { codigo:'8481-10', nome:'Operador de Laticínios', grupo:'Alimentação' },
  { codigo:'8481-15', nome:'Operador de Frigorífico', grupo:'Alimentação' },
  { codigo:'8481-20', nome:'Operador de Bebidas', grupo:'Alimentação' },
  { codigo:'8481-25', nome:'Operador de Moagem', grupo:'Alimentação' },
  { codigo:'8481-30', nome:'Auxiliar de Frigorífico', grupo:'Alimentação' },
  // ── Limpeza e Conservação ────────────────────────────────────
  { codigo:'5143-05', nome:'Faxineiro / Zelador', grupo:'Limpeza' },
  { codigo:'5143-10', nome:'Operador de Lavanderia', grupo:'Limpeza' },
  { codigo:'5143-15', nome:'Auxiliar de Limpeza', grupo:'Limpeza' },
  { codigo:'5143-20', nome:'Gari / Coletador de Resíduos', grupo:'Limpeza' },
  { codigo:'5143-25', nome:'Operador de Varrição', grupo:'Limpeza' },
  { codigo:'5144-05', nome:'Limpador Industrial', grupo:'Limpeza' },
  // ── Agricultura e Pecuária ───────────────────────────────────
  { codigo:'6110-05', nome:'Trabalhador Rural', grupo:'Agrícola' },
  { codigo:'6110-10', nome:'Operador de Colheitadeira', grupo:'Agrícola' },
  { codigo:'6110-15', nome:'Aplicador de Defensivos', grupo:'Agrícola' },
  { codigo:'6110-20', nome:'Irrigador', grupo:'Agrícola' },
  { codigo:'6110-25', nome:'Tratorista Agrícola', grupo:'Agrícola' },
  { codigo:'6110-30', nome:'Operador de Máquinas Agrícolas', grupo:'Agrícola' },
  { codigo:'6110-35', nome:'Trabalhador de Cana-de-Açúcar', grupo:'Agrícola' },
  { codigo:'6110-40', nome:'Trabalhador de Soja', grupo:'Agrícola' },
  { codigo:'6110-45', nome:'Trabalhador de Café', grupo:'Agrícola' },
  { codigo:'6110-50', nome:'Trabalhador de Laranja / Citros', grupo:'Agrícola' },
  { codigo:'6111-05', nome:'Granjeiro / Avicultor', grupo:'Agrícola' },
  { codigo:'6111-10', nome:'Trabalhador em Suinocultura', grupo:'Agrícola' },
  { codigo:'6111-15', nome:'Trabalhador em Bovinocultura', grupo:'Agrícola' },
  { codigo:'6111-20', nome:'Ordenhador', grupo:'Agrícola' },
  { codigo:'6112-05', nome:'Trabalhador Florestal', grupo:'Agrícola' },
  { codigo:'6112-10', nome:'Operador de Motosserra', grupo:'Agrícola' },
  { codigo:'6220-05', nome:'Pescador', grupo:'Pesca' },
  { codigo:'6220-10', nome:'Marisqueiro', grupo:'Pesca' },
  // ── Tecnologia da Informação ─────────────────────────────────
  { codigo:'2123-05', nome:'Analista de Sistemas', grupo:'TI' },
  { codigo:'2123-10', nome:'Desenvolvedor de Software', grupo:'TI' },
  { codigo:'2123-15', nome:'Desenvolvedor Web', grupo:'TI' },
  { codigo:'2123-20', nome:'Desenvolvedor Mobile', grupo:'TI' },
  { codigo:'2123-25', nome:'Analista de Dados', grupo:'TI' },
  { codigo:'2123-30', nome:'Cientista de Dados', grupo:'TI' },
  { codigo:'2124-05', nome:'Analista de Segurança da Informação', grupo:'TI' },
  { codigo:'2124-10', nome:'Arquiteto de Soluções', grupo:'TI' },
  { codigo:'3171-05', nome:'Técnico de Suporte em TI', grupo:'TI' },
  { codigo:'3172-05', nome:'Operador de Computador', grupo:'TI' },
  { codigo:'3172-10', nome:'Técnico em Infraestrutura', grupo:'TI' },
  // ── Educação ─────────────────────────────────────────────────
  { codigo:'2310-05', nome:'Professor de Ensino Superior', grupo:'Educação' },
  { codigo:'2321-05', nome:'Professor de Ensino Médio', grupo:'Educação' },
  { codigo:'2331-05', nome:'Professor de Ensino Fundamental', grupo:'Educação' },
  { codigo:'2332-05', nome:'Professor de Educação Infantil', grupo:'Educação' },
  { codigo:'2340-05', nome:'Professor de Educação Especial', grupo:'Educação' },
  { codigo:'3334-05', nome:'Instrutor de Treinamento e Desenvolvimento', grupo:'Educação' },
  // ── Vigilância e Segurança ───────────────────────────────────
  { codigo:'5173-05', nome:'Vigilante', grupo:'Segurança' },
  { codigo:'5173-10', nome:'Porteiro', grupo:'Segurança' },
  { codigo:'5173-15', nome:'Controlador de Acesso', grupo:'Segurança' },
  { codigo:'5173-20', nome:'Segurança Patrimonial', grupo:'Segurança' },
  { codigo:'5173-25', nome:'Supervisor de Segurança', grupo:'Segurança' },
  { codigo:'5174-05', nome:'Bombeiro Civil', grupo:'Segurança' },
  { codigo:'5174-10', nome:'Brigadista de Incêndio', grupo:'Segurança' },
  // ── Têxtil e Confecção ───────────────────────────────────────
  { codigo:'7912-05', nome:'Costureiro', grupo:'Têxtil' },
  { codigo:'7912-10', nome:'Costureiro Industrial', grupo:'Têxtil' },
  { codigo:'7912-15', nome:'Auxiliar de Costura', grupo:'Têxtil' },
  { codigo:'7921-05', nome:'Trabalhador Têxtil', grupo:'Têxtil' },
  { codigo:'7921-10', nome:'Operador de Máquina de Costura', grupo:'Têxtil' },
  { codigo:'7922-05', nome:'Cortador de Tecido', grupo:'Têxtil' },
  { codigo:'7922-10', nome:'Modelista', grupo:'Têxtil' },
  { codigo:'7922-15', nome:'Bordador', grupo:'Têxtil' },
  // ── Automóveis e Autopeças ───────────────────────────────────
  { codigo:'9112-05', nome:'Mecânico de Automóveis', grupo:'Automotivo' },
  { codigo:'9112-10', nome:'Mecânico de Motos', grupo:'Automotivo' },
  { codigo:'9112-15', nome:'Auxiliar de Mecânico Automotivo', grupo:'Automotivo' },
  { codigo:'9113-05', nome:'Eletricista Automotivo', grupo:'Automotivo' },
  { codigo:'9114-05', nome:'Funileiro Automotivo', grupo:'Automotivo' },
  { codigo:'9115-05', nome:'Pintor Automotivo', grupo:'Automotivo' },
  { codigo:'9116-05', nome:'Alinhador e Balanceador', grupo:'Automotivo' },
  { codigo:'9117-05', nome:'Lubrificador Automotivo', grupo:'Automotivo' },
  { codigo:'9511-05', nome:'Técnico em Diagnóstico Automotivo', grupo:'Automotivo' },
  // ── Madeira e Mobiliário ─────────────────────────────────────
  { codigo:'7711-05', nome:'Marceneiro', grupo:'Madeira' },
  { codigo:'7711-10', nome:'Auxiliar de Marcenaria', grupo:'Madeira' },
  { codigo:'7711-15', nome:'Operador de Serra', grupo:'Madeira' },
  { codigo:'7711-20', nome:'Operador de CNC Móveis', grupo:'Madeira' },
  { codigo:'7712-05', nome:'Carpinteiro de Marcenaria', grupo:'Madeira' },
  { codigo:'7721-05', nome:'Montador de Móveis', grupo:'Madeira' },
  // ── Papel e Celulose ─────────────────────────────────────────
  { codigo:'7651-15', nome:'Operador de Digestor', grupo:'Papel e Celulose' },
  { codigo:'7652-05', nome:'Operador de Caldeira de Recuperação', grupo:'Papel e Celulose' },
  { codigo:'7653-05', nome:'Operador de Branqueamento', grupo:'Papel e Celulose' },
  // ── Borracha e Plástico ──────────────────────────────────────
  { codigo:'7411-05', nome:'Operador de Vulcanização', grupo:'Borracha' },
  { codigo:'7411-10', nome:'Operador de Calandragem', grupo:'Borracha' },
  { codigo:'7412-05', nome:'Operador de Extrusão de Borracha', grupo:'Borracha' },
  { codigo:'7421-05', nome:'Operador de Extrusão de Plástico', grupo:'Plástico' },
  { codigo:'7421-10', nome:'Operador de Sopro de Plástico', grupo:'Plástico' },
  { codigo:'7421-15', nome:'Operador de Injeção de Plástico', grupo:'Plástico' },
  // ── Saúde e Bem-Estar ────────────────────────────────────────
  { codigo:'5162-05', nome:'Cuidador de Idosos', grupo:'Cuidados' },
  { codigo:'5162-10', nome:'Cuidador de Pessoas com Deficiência', grupo:'Cuidados' },
  { codigo:'5162-15', nome:'Auxiliar de Cuidados', grupo:'Cuidados' },
  { codigo:'5163-05', nome:'Atendente de Creche', grupo:'Cuidados' },
  // ── Outros ───────────────────────────────────────────────────
  { codigo:'3514-05', nome:'Técnico em Meio Ambiente', grupo:'Meio Ambiente' },
  { codigo:'3514-10', nome:'Analista Ambiental', grupo:'Meio Ambiente' },
  { codigo:'3515-05', nome:'Técnico em Qualidade', grupo:'Qualidade' },
  { codigo:'3515-10', nome:'Analista de Qualidade', grupo:'Qualidade' },
  { codigo:'3515-15', nome:'Inspetor de Qualidade', grupo:'Qualidade' },
  { codigo:'3515-20', nome:'Auditor de Qualidade', grupo:'Qualidade' },
  { codigo:'3516-10', nome:'Técnico em Meio Ambiente', grupo:'Meio Ambiente' },
  { codigo:'5211-15', nome:'Promotor de Vendas', grupo:'Comercial' },
  { codigo:'5221-05', nome:'Operador de Caixa de Supermercado', grupo:'Comercial' },
  { codigo:'5221-10', nome:'Repositor de Mercadorias', grupo:'Comercial' },
  { codigo:'5231-05', nome:'Balconista', grupo:'Comercial' },
  { codigo:'5241-05', nome:'Frentista de Posto', grupo:'Combustíveis' },
  { codigo:'5241-10', nome:'Operador de Posto de Combustíveis', grupo:'Combustíveis' },
]

export function buscarCBO(termo: string): CBO[] {
  if (!termo || termo.length < 2) return []
  const t = termo.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')
  return CBO_DATA.filter(c => {
    const nome = c.nome.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    const cod  = c.codigo.replace(/\D/g,'')
    return nome.includes(t) || cod.includes(t)
  }).slice(0, 10)
}
